services:
  app:
    image: crocodilestick/calibre-web-automated:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - DOCKER_MODS=lscr.io/linuxserver/mods:universal-calibre
    volumes:
      - app_config:/config
      - $PWD/consume:/cwa-book-ingest
      - app_data:/calibre-library
    networks:
      - proxy_apps
    restart: unless-stopped

networks:
  proxy_apps:
    name: proxy_apps
    external: true

volumes:
  app_config:
  app_data: