services:
  app:
    image: lscr.io/linuxserver/kavita:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - app_data:/config
      - /mnt/media/ebooks:/data:ro
    networks:
      - proxy_apps
    restart: unless-stopped

networks:
  proxy_apps:
    name: proxy_apps
    external: true

volumes:
  app_data: